version: 2
jobs:
  api-test:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/my-fabric/api

    steps:
      - checkout:
          path: ~/my-fabric

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run: sudo npm install -g codecov

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: run tests
          command: |
            npm test
            codecov

  chaincode-test:
    docker:
      - image: circleci/golang:1.12
    working_directory: ~/my-fabric/mychaincode/go
    steps:
      - checkout:
          path: ~/my-fabric
      - run:
          name: Install dependencies
          command: |
            go mod tidy
            go mod download
      - run:
          name: Test chaincode
          command: |
            go test -race -coverprofile=coverage.txt -covermode=atomic
            bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  workflows:
    jobs:
      - api-test
      - chaincode-test